### ISSUE TITLE
More descriptive vendor and package name

### ISSUE THREAD

**Issue by szepeviktor** [GraphQLAPI/graphql-api-for-wp#17]
`graphql-api/graphql-api` seems to be too general for me.
Similar to _X Barista School_ choosing baristaschool.com domain name instead of x.com.

The vendor name could tell _who_ is making the package,
the packager name could tell a bit more about _what we do_ here.

What do you think about`pop/graphql-api4wp`?

**Comment by szepeviktor** [comment]
There are only 2 ancient packages with `pop` as vendor https://packagist.org/packages/pop/

**Comment by leoloso** [comment]
These are good questions. Thanks for caring about this issue!

> `graphql-api/graphql-api` seems to be too general for me.

There are a couple of reasons why I'm using `graphql-api`: 

1. Because I've registered the domain graphql-api.com (I'm working on the site, I hope to have it ready in a week or two).
2. Because, I hope, the WordPress implementation is only the first one, and other ones will eventually be implemented, eg for Laravel. Then, "GraphQL API" would be the umbrella name for all of them.

In this last sense, have you checked [graphql-by-pop.com](https://graphql-by-pop.com/)? GraphQL by PoP is the actual GraphQL server, and it is CMS-agnostic. It comprises around 90% of the code to implement a GraphQL server. The code for the actual CMS is only around 10% (I'm talking about PHP code. WordPress also demanded additional JS code to configure the server through Gutenberg). Then, with only a bit of effort, it can be ported to other platforms.

> What do you think about `pop/graphql-api4wp`?

I use `GraphQLAPI` for this plugin instead of `PoP`, because [PoP](https://github.com/leoloso/PoP) corresponds to a more general application: it's the server-side components architecture that enables to build a GraphQL server. 

In other words: GraphQL is just one application among the many possible from using the architecture from PoP! `PoP >= GraphQL`!

For instance:

- REST APIs: [this is a REST endpoint to fetch posts](https://newapi.getpop.org/posts/api/rest/), and it's the same code powering the `Post` type for the GraphQL server
- Websites: [getpop.org](https://getpop.org) is a website completely built using server-side components. (The website is slow, because I haven't updated it in more than 2 years... it's running an earlier version of PoP, incompatible with the current one, and I must still work on the migration)

That's why I'm using different organizations in GitHub to manage the code:

- [PoP](https://github.com/getpop): the server-side component architecture. It's responsible for loading the data from the components (which is more efficient than a graph, and can satisfy the graph too, as explained [in this article](https://www.smashingmagazine.com/2019/01/introducing-component-based-api/))
- [PoPSchema](https://github.com/PoPSchema): entities from the schema. Please notice: there's no GraphQL here! These entities load their data, for whichever output it will be used for: GraphQL, REST, website, etc
- [GraphQLByPoP](https://github.com/GraphQLByPoP): this is the first layer implementing the GraphQL server, which is CMS-agnostic
- [GraphQLAPI](https://github.com/GraphQLAPI): the different GraphQL implementations, currently only the one for WordPress

> There are only 2 ancient packages with pop as vendor https://packagist.org/packages/pop/

I chose to use `getpop` instead of `pop`, because username `pop` in packagist was already taken... If I could take over it, I'd certainly do it...

**Comment by szepeviktor** [comment]
Basically "GraphQLAPI / graphql-api" does not tell you it is for WordPress :)

**Comment by leoloso** [comment]
So you'd rather have `GraphQLAPI/graphql-api-for-wp`?

**Comment by szepeviktor** [comment]
No, I'm just revealing the problem and leaving it up to You.

**Comment by leoloso** [comment]
Alright, I'll think about it

**Comment by leoloso** [comment]
Alright, you convinced me :) I've renamed the repo!

**Comment by leoloso** [comment]
This issue (I believe) is resolved, so I'm closing it
